<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<PublishAot>true</PublishAot>
		<InvariantGlobalization>true</InvariantGlobalization>
		<RootNamespace>ProxiedHosts.Console</RootNamespace>
		<AssemblyName>proxiedhosts</AssemblyName>
		<!-- Set as false to see full analysis details. Default is true. -->
		<TrimmerSingleWarn>true</TrimmerSingleWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ProxiedHosts.Core\ProxiedHosts.Core.csproj" />
	</ItemGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<!-- Excludes *.pdb files from the publish directory so they don't end up in the final packaging. -->
		<CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
	</PropertyGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
			<_Parameter1>Authors</_Parameter1>
			<_Parameter2>$(Authors)</_Parameter2>
		</AssemblyAttribute>
	</ItemGroup>

</Project>
