<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<PublishAot>true</PublishAot>
		<IsAotCompatible>true</IsAotCompatible>
		<InvariantGlobalization>true</InvariantGlobalization>
		<RootNamespace>ProxiedHosts.Tray</RootNamespace>
		<AssemblyName>proxiedhosts-tray</AssemblyName>
		<ApplicationIcon>Assets/ProxiedHosts.ico</ApplicationIcon>
		<!-- Set as false to see full analysis details. Default is true. -->
		<TrimmerSingleWarn>true</TrimmerSingleWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ProxiedHosts.Core\ProxiedHosts.Core.csproj" />
		<PackageReference Include="Avalonia.Desktop" Version="12.1.3" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.3" />
	</ItemGroup>
	
	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<!-- Excludes *.pdb files from the publish directory to avoid macOS bundle signing issues. -->
		<CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
		<!-- Does the same for debugging symbols from referenced nuget packages. -->
		<PublishReferencesSymbols>false</PublishReferencesSymbols>
	</PropertyGroup>

	<!-- Remove debugging symbols from Release publish output when above is ignored. -->
	<Target Name="RemovePublishedPdbFiles" AfterTargets="Publish" Condition="'$(Configuration)' == 'Release' and '$(PublishDir)' != ''">
		<ItemGroup>
			<_PublishedPdbFiles Include="$(PublishDir)**/*.pdb" />
		</ItemGroup>

		<Delete Files="@(_PublishedPdbFiles)" />
	</Target>

	<ItemGroup>
		<AvaloniaResource Include="Assets/**" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Assets\" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
			<_Parameter1>Authors</_Parameter1>
			<_Parameter2>$(Authors)</_Parameter2>
		</AssemblyAttribute>

		<AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
			<_Parameter1>DonationUrl</_Parameter1>
			<_Parameter2>$(DonationUrl)</_Parameter2>
		</AssemblyAttribute>

		<AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
			<_Parameter1>FixedDonationUrl</_Parameter1>
			<_Parameter2>$(FixedDonationUrl)</_Parameter2>
		</AssemblyAttribute>

		<EmbeddedResource Include="..\LICENSE" LogicalName="ProxiedHosts.LICENSE" />
	</ItemGroup>

</Project>