<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<PublishAot>true</PublishAot>
		<IsAotCompatible>true</IsAotCompatible>
		<InvariantGlobalization>true</InvariantGlobalization>
		<RootNamespace>ProxiedHosts.Tray</RootNamespace>
		<AssemblyName>proxiedhosts-tray</AssemblyName>

		<!-- Set as false to see full analysis details. Default is true. -->
		<TrimmerSingleWarn>true</TrimmerSingleWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ProxiedHosts.Core\ProxiedHosts.Core.csproj" />
		<PackageReference Include="Avalonia.Desktop" Version="12.1.3" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.3" />
	</ItemGroup>
	
	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<!-- Excludes *.pdb files from the publish directory to avoid macOS bundle signing issues. -->
		<CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
	</PropertyGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets/**" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Assets\" />
	</ItemGroup>

</Project>